### PR TITLE
14

### PR DESCRIPTION
**Pull request by hostilefork**
(redacted)

### CODE REVIEW

**Comment by phma** [comment]
I cloned bezitopo to my new laptop, compiled it, ran bezitest, and got a fail on the DXF test and a crash on one of the geodesy tests. It ran fine on my old dev box. I ran it on my old dev box and it finished fine. I'm running it in gdb to find out what's wrong.

Bezitopo isn't ready for use (though I've been using it, mostly to convert CSV files from one format to another, occasionally to compute alignments from measured points), and there are some things to do before I can make it a usable CAD program. If you'd like to test something that is ready for use, try perfecttin.

I just found a bug in my cipher and hash WringTwistree (Julia version) and am documenting all public functions and types, so it'll be a while before I get around to reviewing your pull request.

I also had one unpushed change in Bezitopo which relates to a total station I bought a few months ago.

Can you explain why I'd want continuous integration? Is it available on BSD, on POWER (in particular on big-endian hardware and OS), and on ARM? There's one constant that needs to be computed on a POWER box because it has 128-bit floats.

**Comment by hostilefork** [comment]
The value of continuous integration is self-evident.

Your release build didn't compile due to a simple oversight of `#ifndef DEBUG` instead of `#ifndef NDEBUG`.  Why wouldn't you want something that does a release build on every commit for you, finding these things instead of waiting until the day you happen to decide to make a release build?

There are ARM-hosted runners:

  https://github.blog/news-insights/product-news/arm64-on-github-actions-powering-faster-more-efficient-build-systems/

But other architectures you can use cross-compilation and simulators, e.g. QEMU:

  https://www.qemu.org/docs/master/system/target-ppc.html

However I'd guess that 99% of bugs are cross-platform.  If something doesn't compile and run successfully on Linux and Windows, it probably won't magically run on PowerPC.

Anyway, you gave me your business card, I was being nice and looking at what you do and seeing if I could make a friend.  Maybe not.  Oh well.

**Comment by phma** [comment]
You mean we've met in person? When and where?

I pushed a fix for the bezitest bug.

**Comment by hostilefork** [comment]
At the now unfortunately gone Zillacoah beer company, in the last of its existence.  I've been in Florida, am returning to Asheville this weekend...

You may do as you wish regarding the changes.  "לא הביישן למד ולא הקפדן מלמד"

**Comment by phma** [comment]
I'm reviewing the pull request, and I find this in `hnum.cpp`:
```
+// However that is only a compile-time constant in C++11 or higher, so would
+// need to commit to building as C++11.
```
It's already noted as being C++11 in `CMakeLists.txt`; when I add threads, I'll up it to C++17 or higher, so that I can get readers-writer locks (which PerfectTIN uses extensively). 

"that is only a compile-time constant" implies "that is not a run-time constant", or what?

**Comment by phma** [comment]
Merged. I had to fix a bug which you introduced in the DXF module, but couldn't test because a bug in CMakeLists made the DXF test crash.

We're meeting at Asheville Pizza on Merrimon. Will you be at the meeting anytime soon?

**Comment by hostilefork** [comment]
Will attend programming Meetups in most cases unless I have conflicting plans.

Currently no location listed for Jan 2 of Asheville Coders League on Meetup.com - is this what's meeting for pizza?

https://www.meetup.com/asheville-coders-league/events/305073764/

**Comment by phma** [comment]
The meetup two weeks ago was at Asheville Pizza, but Jay forgot to set the location. I checked this week and no one had signed up, not even Jay. Watch Slack for an announcement.

**Comment by hostilefork** [comment]
So I'm actually skipping Meetups at the moment, in part due to what I think of your bad behavior in terms of this PR.

You did... however... thank me in the credits (?)

Are you actually grateful that I took that time out of my day, or did you do that because you thought you had to, or what?

**Pull request merged**
